packages:
  - packages/cli
  - packages/core
  - packages/instrument
  - packages/browser
  - apps/*
  - apps/server/src/dashboard

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - protobufjs
